# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: 
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    # The type of runner that the job will run on
      - name: Build armv7hl
        id: build_armv7hl
        #uses: docker://coderus/sailfishos-platform-sdk:4.0.1.45
        uses: coderus/github-sfos-build@master
        with:
          release: 4.0.1.45
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: rpmbuild -bb --build-in-place rpm/*spec
